    global:
      scrape_interval: 5s
      scrape_timeout: 5s
      external_labels:
        monitor: 'Prometheus'

    scrape_configs:
      - job_name: 'k3d-servers'
        static_configs:
          - targets:
              - 172.22.0.2:30910
              - 172.22.0.3:30910
              - 172.22.0.4:30910
              - 172.22.0.5:30910
        relabel_configs:
          - source_labels: [__address__]
            regex: '172.22.0.2:30910'
            target_label: instance
            replacement: 'control-plane'
          - source_labels: [__address__]
            regex: '172.22.0.3:30910'
            target_label: instance
            replacement: 'server-1'
          - source_labels: [__address__]
            regex: '172.22.0.4:30910'
            target_label: instance
            replacement: 'worker'
          - source_labels: [__address__]
            regex: '172.22.0.5:30910'
            target_label: instance
            replacement: 'worker2'
