---
- name: Inject node ip to template
  template:
    src: ../terraform/antrea_traffic_splitting/echo1.tf.j2
    dest: ../terraform/antrea_traffic_splitting/echo1.tf
  vars:
    NODE_1: "{{ k_node_1.stdout }}"

- name: Inject node ip to template
  template:
    src: ../terraform/antrea_traffic_splitting/echo2.tf.j2
    dest: ../terraform/antrea_traffic_splitting/echo2.tf
  vars:
    NODE_2: "{{ k_node_2.stdout }}"

- name: Deploy traffic-splitting scenario
  shell: terraform -chdir=../terraform/antrea_traffic_splitting apply -auto-approve