- name: Get ip to create egress node
  shell: kubectl get nodes -o wide | grep {{ egress_node_agent_name }} | awk '{ print $6 }'
  register: ip

- name: Inject ip pool to template
  template:
    src: roles/deploy_antrea_egress_gateway/templates/egress.yml.j2
    dest: /tmp/egress.yml
  vars:
    egress_ip: "{{ ip.stdout }}"