---
- name: Install specific version of Cilium CLI
  command: cilium install --version 1.15.7 --set=ipam.operator.clusterPoolIPv4PodCIDRList="{{ IP_POOL }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
