- name: Register cilium prometheus.yml
  shell: cat roles/monitoring_cloud/templates/cilium_prometheus.yml
  register: prom_config

- name: Fillup config from template
  template:
    src: roles/monitoring_cloud/templates/prometheus_config_map.yml.j2
    dest: roles/monitoring_cloud/templates/prometheus.yml
  vars:
    prometheus_config: "{{ prom_config.stdout }}"

# - name: Get ip base
#   shell: kubectl get nodes -o wide | grep worker | awk '{ print $6 }' | cut -d'.' -f1-3 | head -n 1
#   register: ip_base

# - name: Fillup config from template
#   template:
#     src: /tmp/monitoring.yml.j2
#     dest: /tmp/config_map.yml
#   vars:
#     ip_addr: "{{ ip_base.stdout }}"

- name: Load configmap with dashboards and victoria metrics using terraform
  shell: terraform -chdir="roles/monitoring_cloud/templates/terraform" apply -auto-approve

- name: Create yaml
  shell: cat roles/monitoring_cloud/templates/monitoring.yml > /tmp/monitoring.yml

- name: Append prometheus
  shell: cat roles/monitoring_cloud/templates/prometheus.yml >> /tmp/monitoring.yml

- name: Append node_exporter
  shell: cat roles/monitoring_cloud/templates/node_exporter.yml >> /tmp/monitoring.yml

- name: Apply /tmp/monitoring.yml
  shell: kubectl apply -f /tmp/monitoring.yml

# - name: Apply cadvisor
#   shell: kubectl apply -f roles/monitoring_cloud/templates/cadvisor.yml

- name: Wait until grafana ready
  shell: kubectl wait --timeout=5m -n monitoring deployment/grafana --for=condition=Available
