---
- name: Download kubectl
  shell: curl -o /tmp/kubectl -L "https://dl.k8s.io/release/v1.30.2/bin/linux/amd64/kubectl"
  args:
    creates: /tmp/kubectl

- name: Download checksum
  shell: curl -o /tmp/kubectl.sha256 -L "https://dl.k8s.io/release/v1.30.2/bin/linux/amd64/kubectl.sha256"
  args:
    creates: /tmp/kubectl.sha256

- name: Validate checksum
  shell: "echo $(cat /tmp/kubectl.sha256) /tmp/kubectl | sha256sum --check"
  register: sha256sum_result
  failed_when: "'OK' not in sha256sum_result.stdout"

- name: Install kubectl
  command: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
  become: yes
  when: "'OK' in sha256sum_result.stdout"