---
- name: Delete the Calico operator
  command: kubectl delete -f roles/common_calico/templates/tigera-operator.yaml --force
  ignore_errors: yes

- name: Delete Calico custom resource
  command: kubectl delete -f roles/common_calico/templates/custom-resources.yaml --force
  ignore_errors: yes

- name: Remove CNI
  command: rm -f /etc/cni/net.d/10-calico.conflist
  become: yes

- name: Remove CNI
  command: rm -f /etc/cni/net.d/calico-kubeconfig
  become: yes