---
- name: Delete Antrea
  command: kubectl delete -f roles/setup_k3s_antrea/templates/antrea.yml
  ignore_errors: yes

- name: Remove CNI
  command: rm -f /etc/cni/net.d/10-antrea.conflist
  become: yes
