{
 "title": "Statexec Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(statexec_command_status,instance)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(statexec_command_status{instance=~\"$instance\"},role)"
    }
   },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Summary for \"$instance\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Average metrics for \"$instance\" ($role)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "role",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(statexec_summary_cpu_mean_seconds{instance=~\"$instance\",role=~\"$role\",mode=~\"user|system\"}) by (mode)",
     "legendFormat": "CPU {{mode}}"
    },
    {
     "expr": "statexec_summary_cpu_cores{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "CPU total"
    },
    {
     "expr": "statexec_summary_memory_used_bytes{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "MEM Used"
    },
    {
     "expr": "statexec_summary_memory_total_bytes{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "MEM Total"
    },
    {
     "expr": "statexec_summary_network_mean_received_bytes_per_second{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "NET Recv"
    },
    {
     "expr": "statexec_summary_network_mean_sent_bytes_per_second{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "NET Sent"
    },
    {
     "expr": "statexec_summary_disk_mean_read_bytes_per_second{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "statexec_summary_disk_mean_write_bytes_per_second{instance=~\"$instance\",role=~\"$role\"}",
     "legendFormat": "Disk Write"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_cpu_seconds_total{instance=~\"$instance\"}[1s])) by (instance,role,mode)",
     "legendFormat": "{{instance}}/{{role}} {{mode}}"
    },
    {
     "expr": "sum(rate(statexec_cpu_seconds_total{instance=~\"$instance\"}[1s])) by (instance,role)",
     "legendFormat": "{{instance}}/{{role}} total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "statexec_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{role}} used"
    },
    {
     "expr": "statexec_memory_buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{role}} buffers"
    },
    {
     "expr": "statexec_memory_cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{role}} cached"
    },
    {
     "expr": "statexec_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/{{role}} total"
    }
   ]
  },
  {
   "title": "Network Bandwidth in bit/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{instance=~\"$instance\"}[1s]) * 8) by (instance,role,interface)",
     "legendFormat": "[{{instance}}/{{role}}] {{interface}} in"
    },
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{instance=~\"$instance\"}[1s]) * 8) by (instance,role,interface)",
     "legendFormat": "[{{instance}}/{{role}}] {{interface}} out"
    }
   ]
  },
  {
   "title": "Disk Bandwidth in bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_disk_read_bytes_total{instance=~\"$instance\"}[1s]) * 8) by (instance,role,interface)\n",
     "legendFormat": "[{{instance}}/{{role}}] {{interface}} read"
    },
    {
     "expr": "sum(rate(statexec_disk_write_bytes_total{instance=~\"$instance\"}[1s]) * 8) by (instance,role,interface)",
     "legendFormat": "[{{instance}}/{{role}}] {{interface}} write"
    }
   ]
  }
 ]
}