---
- name: Show NODE_1 IP
  debug:
    msg: "NODE_1 IP: {{ k_node_1.stdout }}"

- name: Show NODE_2 IP
  debug:
    msg: "NODE_2 IP: {{ k_node_2.stdout }}"

- name: Inject node ip to template
  template:
    src: ../terraform/cilium_traffic_splitting/echo1.tf.j2
    dest: ../terraform/cilium_traffic_splitting/echo1.tf
  vars:
    NODE_1: "{{ k_node_1.stdout }}"

- name: Inject node ip to template
  template:
    src: ../terraform/cilium_traffic_splitting/echo2.tf.j2
    dest: ../terraform/cilium_traffic_splitting/echo2.tf
  vars:
    NODE_2: "{{ k_node_2.stdout }}"

- name: Deploy traffic-splitting scenario
  shell: terraform -chdir=../terraform/cilium_traffic_splitting apply -auto-approve