---
- name: Delete antrea-gw0 interface
  command: ip link delete antrea-gw0
  ignore_errors: yes
  become: yes

- name: Delete vxlan.calico interface
  command: ip link delete vxlan.calico
  ignore_errors: yes
  become: yes

- name: Delete cilium_net interface
  command: ip link delete cilium_net
  ignore_errors: yes
  become: yes

- name: Delete cilium_host interface
  command: ip link delete cilium_host
  ignore_errors: yes
  become: yes

- name: Delete cilium_vxlan interface
  command: ip link delete cilium_vxlan
  ignore_errors: yes
  become: yes
