- name: Get victoriametrics ip
  shell: kubectl get nodes -o wide | grep agent-0 | awk '{ print $6 }' | cut -d'.' -f1-3
  register: vm_server_ip

- name: Upload metrics to victoriametrics
  shell: roles/upload_statexec_metrics/templates/upload.sh
  vars:
    GRAFANA: "{{ vm_server_ip }}:30303"
    METRICS_PATH: "{{ volume_mount_path }}"
    VMSERVER: "{{ vm_server_ip }}:30842"