      - job_name: 'kind-servers'
        static_configs:
          - targets:
              - "{{ ip_addr_1 }}:30910"
              - "{{ ip_addr_2 }}:30910"
              - "{{ ip_addr_3 }}:30910"
        relabel_configs:
          - source_labels: [__address__]
            regex: "{{ ip_addr_1 }}:30910"
            target_label: instance
            replacement: 'control-plane'
          - source_labels: [__address__]
            regex: "{{ ip_addr_2 }}:30910"
            target_label: instance
            replacement: 'worker'
          - source_labels: [__address__]
            regex: "{{ ip_addr_3 }}:30910"
            target_label: instance
            replacement: 'worker2'