      - job_name: 'k3d-servers'
        static_configs:
          - targets:
              - "{{ ip_addr }}.2:30910"
              - "{{ ip_addr }}.3:30910"
              - "{{ ip_addr }}.4:30910"
        relabel_configs:
          - source_labels: [__address__]
            regex: "{{ ip_addr }}.2:30910"
            target_label: instance
            replacement: 'control-plane'
          - source_labels: [__address__]
            regex: "{{ ip_addr }}.3:30910"
            target_label: instance
            replacement: 'worker'
          - source_labels: [__address__]
            regex: "{{ ip_addr }}.4:30910"
            target_label: instance
            replacement: 'worker2'