apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    layer2:
      addresses:
        - 172.19.0.2/32
        - 172.19.0.3/32
        - 172.19.0.4/32
