      - job_name: 'aks-servers'
        static_configs:
          - targets:
              - "10.224.0.4:30910"
              - "10.224.0.5:30910"
        relabel_configs:
          - source_labels: [__address__]
            regex: "10.224.0.4:30910"
            target_label: instance
            replacement: 'aks-0'
          - source_labels: [__address__]
            regex: "10.224.0.5:30910"
            target_label: instance
            replacement: 'aks-1'