---
- name: Install metallb
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml

- name: Configure metallb
  shell: kubectl wait --timeout=10m -n metallb-system deployment/controller --for=condition=Available

- name: Get network ip # assume /16 subnet
  shell: docker network inspect kind | jq -r '.[0].IPAM.Config[1] | .Subnet' | cut -d'/' -f1
  register: network_ip

- name: Specify ip pool
  shell: echo "$(echo {{ network_ip.stdout }} | sed 's|\.0\.0|\.0\.50|')-$(echo {{ network_ip.stdout }} | sed 's|\.0\.0|\.0\.100|')"
  register: ip_pool

- name: Inject ip pool to template
  template:
    src: roles/install_metallb/templates/metallb_values.yaml.j2
    dest: /tmp/metallb_values.yaml
  vars:
    IP_POOL: "{{ ip_pool.stdout }}"


- name: Configure metallb
  shell: kubectl apply -f /tmp/metallb_values.yaml

#
# - name: Restart metallb deployment
#   shell: kubectl rollout restart deployment -n metallb-system

