kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0
    extraMounts:
    - hostPath: /mnt/kind
      containerPath: /host_shared_data
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
  - role: worker
    image: kindest/node:v1.31.0
    extraMounts:
    - hostPath: /mnt/kind
      containerPath: /host_shared_data
  - role: worker
    image: kindest/node:v1.31.0
    extraMounts:
    - hostPath: /mnt/kind
      containerPath: /host_shared_data
