---
- name: Create antrea egress scenario with egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml
    - ./vars/egress_gateway.yml
    - ./vars/antrea.yml

  roles:
    - create_k3d_cluster
    - install_antrea
    - get_ip_for_egress_node
    - deploy_antrea_egress_gateway
    - terraform_run_egress_iperf

