---
- name: Create antrea egress scenario without egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/antrea.yml
    - ./vars/common.yml
    - ./vars/egress_no_gateway.yml
    - ./vars/local.yml

  roles:
    - create_kind_cluster
    - install_antrea
    - wait_until_antrea_installed
    - monitoring
    - terraform_run_egress_iperf
    - scrap_prometheus_data
