---
- name: Create antrea ingress scenario with gateway api
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/antrea.yml
    - ./vars/cloud.yml
    - ./vars/common.yml
    - ./vars/traffic_splitting.yml

  roles:
    - create_azure_cluster
    - install_antrea_cloud
    - wait_until_antrea_installed
    - install_gateway_crd
    - install_nginx_gateway
    - deploy_antrea_gateway_api_scenario
    - monitoring
    - register_gateway_api_ip
    - run_k6
    - scrap_prometheus_data
