---
- name: Create antrea egress scenario with egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml
    - ./vars/traffic_splitting.yml
    - ./vars/antrea.yml

  roles:
    - create_k3d_cluster
    - install_antrea
    - wait_until_antrea_installed
    - install_gateway_crd
    - install_nginx_gateway
    - deploy_antrea_gateway_api_scenario
    - monitoring
    - run_traffic_shaping_k6
