---
- name: Create cilium egress scenario with egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/cilium.yml
    - ./vars/common.yml
    - ./vars/egress_gateway.yml
    - ./vars/local.yml

  roles:
    - create_kind_cluster
    - install_cilium_with_helm
    - wait_for_cilium_install
    - set_egress_node
    - get_ip_for_egress_node
    - deploy_cilium_egress_gateway
    - monitoring
    - terraform_run_egress_iperf
    - scrap_prometheus_data

