---
- name: Create cilium egress scenario with egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml
    - ./vars/egress_gateway.yml
    - ./vars/cilium.yml
    - ./vars/cloud.yml

  roles:
   - create_azure_cluster
  #  - set_egress_node
  #  - get_ip_for_egress_node
  #  - deploy_cilium_egress_gateway
  #  - monitoring
  #  - terraform_run_egress_iperf

