---
- name: Create cluster and install cilium cni plugin for traffic splitting
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/traffic_splitting.yml
    - ./vars/cilium.yml
    - ./vars/common.yml
    - ./vars/local.yml

  roles:
  # - create_kind_cluster
  # - install_gateway_crd # Before cilium is a must!
  # - install_cilium_with_helm
  # - wait_for_cilium_install
  # - install_metallb
  # - register_nodes
  # - register_gateway_api_ip
  # - deploy_cilium_gateway_api_scenario
  # - monitoring
    - register_gateway_api_ip
    - run_traffic_shaping_k6
    - scrap_prometheus_data
