---
- name: Create cilium egress scenario without egress gateway
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml
    - ./vars/egress_no_gateway.yml
    - ./vars/cilium.yml

  roles:
    - create_k3d_cluster
    - install_cilium_with_helm
    - enable_hubble
    - wait_for_cilium_install
    - monitoring
    - terraform_run_egress_iperf

