---
- name: Create cluster and install cilium cni plugin for traffic splitting
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/traffic_splitting.yml
    - ./vars/cilium.yml
    - ./vars/common.yml

  roles:
    - create_k3d_cluster
    - install_gateway_crd # Before cilium is a must!
    - install_cilium_with_helm
    - enable_hubble
    - wait_for_cilium_install
    - deploy_cilium_gateway_api_scenario
    - monitoring
    - run_traffic_shaping_k6
