---
- name: Create cilium ingress scenario with gateway api
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/cilium.yml
    - ./vars/cloud.yml
    - ./vars/common.yml
    - ./vars/traffic_splitting.yml

  roles:
    - create_azure_cluster
    - install_gateway_crd
    - install_cilium_with_helm
    - wait_for_cilium_install
    - register_nodes
    - deploy_cilium_gateway_api_scenario_cloud
    - monitoring
    - register_gateway_api_ip
    - run_k6
    - scrap_prometheus_data