---
- name: Create cluster and install cilium cni plugin for traffic splitting
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/traffic_splitting.yml
    - ./vars/cilium.yml
    - ./vars/common.yml

  roles:
#   - create_kind_cluster
#   - install_gateway_crd # Before cilium is a must!
#   - install_cilium_with_helm
#    - enable_hubbleremove_kube_proxy
#   - wait_for_cilium_install
#   - remove_kube_proxy
#   - install_metallb
#   - deploy_cilium_gateway_api_scenario_cloud
#   - monitoring
#   - monitoring_cloud
   - run_traffic_shaping_k6
