apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: nginx
    name: nginx
    command:
    - /bin/sh
    - -c
    securityContext:
      capabilities:
        add:
          - NET_ADMIN  # Add the cap_net_admin capability
    env:
    - name: EGRESS_IPS
      value: 192.168.11.5/24, 192.168.11.4/24
    resources: {}
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/hostname: fedora
  restartPolicy: Always
status: {}
