apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  destinationCIDRs:
  - "0.0.0.0/0"
  selectors:
  - podSelector: {}
  egressGateway:
    nodeSelector:
      matchLabels:
        egress-node: "true"