---
- name: Setup Calico on k3s
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml

  roles:
    - delete_calico
    - delete_cilium
    - uninstall_k3s
    - setup_k3s_calico
