---
- name: Setup Antrea on k3s
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/antrea.yml

  roles:
    - ask_for_password
    - delete_calico
    - delete_cilium
    - delete_antrea
    - uninstall_k3s
    - delete_cni
    - delete_network_interfaces
    - install_k3s
    - setup_k3s_antrea
