---
- name: Install k3s
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/default.yml

  roles:
    - ask_for_password
    - delete_calico
    - delete_cilium
    - delete_antrea
    - uninstall_k3s
    - delete_cni
    - delete_network_interfaces
    - install_kubectl
    - install_k3s