---
- name: Create cluster and install cilium cni plugin
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/cilium.yml
    - ./vars/common.yml

  roles:
    - create_k3d_cluster
    - install_cilium

