---
- name: Prepare environment
  hosts: "{{ target | default('localhost') }}"
  vars_files:
    - ./vars/common.yml

  roles:
    - ask_for_password
    - install_k3d
    - install_kubectl
    - install_cilium_cli