---
- name: Start egress scenario
  hosts: "{{ target | default('localhost') }}"
  vars_prompt:
    - name: cni
      prompt: "Choose cni plugin \n1) Calico\n2) Cilium\n"
      private: no

  roles:
    - set_cni_plugin
    - set_egress_node

